version: '3.7'

services:
  deployment:
    image: ivanduka/deployment
    ports:
      - 3333:3333
    environment:
      SLEEP: 0
    healthcheck:
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 1s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
        monitor: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 2s
        monitor: 2s
        order: start-first
