on: [push]
jobs:

#  deploy:
#    name: Deploy
#    needs: setup
#    runs-on: ubuntu-20.04
#    steps:
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          script: |
#            whoami
#            ls -alh

  build:
    name: Build image and upload it to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: set_vars
        run: |
          export TZ=America/Vancouver
          date +'%Y-%m-%dT%H:%M:%S' > CURRENT_TIMESTAMP
          echo $GITHUB_SHA | cut -c1-8 > SHORT_SHA
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Output variables
        run: |
          echo "OUTPUT: ivanduka/deployment:$(cat SHORT_SHA)"
          echo "OUTPUT: $(cat CURRENT_TIMESTAMP)"
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-10)" >> $GITHUB_ENV
          echo ${{env.GITHUB_SHA_SHORT}}
          echo ${{ env.GITHUB_SHA_SHORT }}
          echo ${{ $env.GITHUB_SHA_SHORT }}
          echo ${{$env.GITHUB_SHA_SHORT}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ivanduka/deployment:${{env.GITHUB_SHA_SHORT}}