on: [ push ]
jobs:
  build:
    name: Build image, upload it to Docker Hub, and deploy to server
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker service update deployment_deployment --image=ivanduka/deployment:201 > output
            cat ./output
            cat ./output | grep -i roll -q # only need status 0 or 1
            export rollback=$?
            echo # for extra line
            docker service ps deployment_deployment
            echo # for extra line
            if [ $rollback = 1 ];
             then
               echo "SUCCESS! (no rollback)"
             else
               echo "FAIL! (rollback observed)"
               exit 1
            fi

#      - name: Set Variables
#        run: |
#          export TZ=America/Vancouver
#          echo "CURRENT_TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
#          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV
#
#      - name: copy file via ssh
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          overwrite: true
#          source: "docker-compose.yml"
#          target: "deployment"
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: |
#            ivanduka/deployment:${{ env.GITHUB_SHA_SHORT }}
#            ivanduka/deployment:prod
#
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          script_stop: true
#          script: GITHUB_SHA_SHORT=${{ env.GITHUB_SHA_SHORT }} docker service update deployment_deployment
#            --image=ivanduka/deployment:${{ env.GITHUB_SHA_SHORT }}