on: [push]
jobs:

#  deploy:
#    name: Deploy
#    needs: setup
#    runs-on: ubuntu-20.04
#    steps:
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          script: |
#            whoami
#            ls -alh

  build:
    name: Build image and upload it to Docker Hub
    runs-on: ubuntu-20.04
    env:
      CURRENT_DATETIME: $(date +'%Y-%m-%dT%H:%M:%S')
      SHORT_SHA: ${env.GITHUB_SHA} | cut -c1-8
    steps:
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Output variables
        run: |
          echo "OUTPUT: ivanduka/deployment:${env.SHORT_SHA}"
          echo "OUTPUT: ${env.CURRENT_DATETIME}"
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ivanduka/deployment:${SHORT_SHA}